const products = [
    {
        '_id': '1',
        'name': 'FaZe Hoodie',
        'image': '/images/FaZe_Hoodie.jpeg',
        'description': 'DESIGNED AND PRODUCED LOCALLY IN LOS ANGELES. 9 OZ. 50/50 COTTON/POLYESTER. TRUE TO SIZE STANDARD FIT. SHIPS IN 3-4 WEEKS',
        'brand': 'FaZe',
        'category': 'Hoodies',
        'price': 59.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Globe Hoodie',
        'image': '/images/NRG_Hoodie.jpeg',
        'description': 'LONG SLEEVE PULLOVER HOODIE IN BLACK WITH PRINTED NRG GLOBE LOGO ON FRONT. Please allow up to 10 business days before shipping. Expedited shipping does not accelerate the production process. Delays may occur during limited releases.',
        'brand': 'NRG',
        'category': 'Hoodies',
        'price': 64.99,
        'countInStock': 15,
        'rating': 4.8,
        'numReviews': 20,
    },
    {
        '_id': '3',
        'name': 'TSM Jacket',
        'image': '/images/TSM_Jacket.jpeg',
        'brand': 'TSM',
        'description': 'Product color: Black. 100% Polyester. ',
        'category': 'Jackets',
        'price': 69.99,
        'countInStock': 1,
        'rating': 4.4,
        'numReviews': 8,
    },
    {
        '_id': '4',
        'name': 'G-SHOCK X FAZE CLAN',
        'image': '/images/G-Shock-FaZe-Watch.jpeg',
        'description': 'THE LIMITED-EDITION COLLABORATIVE TIMEPIECE IS CLOAKED IN FAZE CLAN’S SIGNATURE RED TIGER CAMO PRINT PAYING HOMAGE TO THE EARLY DAYS OF FAZE CLAN WHEN MEMBERS WOULD HAVE RED TIGER CAMO SKINS ON THEIR IN-GAME SNIPER RIFLES. THE CASE BACK FEATURES AN ENGRAVING COMMEMORATING FAZE CLAN’S 10-YEAR ANNIVERSARY THIS YEAR.',
        'brand': 'FaZe',
        'category': 'Accessories',
        'price': 149.99,
        'countInStock': 3,
        'rating': 4.9,
        'numReviews': 20,
    },
    {   '_id': '5',
        'name': 'G2 PRO KIT JERSEY 2021',
        'image': '/images/G2-PRO-KIT-JERSEY-2021.jpeg',
        'description': 'The official 2021 Pro Kit jersey of G2 Esports. Made with AEROREADY 100% Recycled Polyester technology, the premium fabric allows for fast drying, no odor, and comfort in every climate. Proudly created and designed with adidas for the #G2ARMY with love, this is the jersey G2 Pro Players will compete in throughout 2021.',  
        'brand': 'G2',
        'category': 'Jerseys',
        'price': 94.99,
        'countInStock': 8,
        'rating': 4.1,
        'numReviews': 26,
    },
]

export default products